[package]
name = "lerna"
version = "0.2.0"
authors = ["Michael Rawson <michael@rawsons.uk>"]
description = "an intelligent theorem prover"
edition = "2018"

[dependencies]
chashmap = "2.2"
crossbeam = "0.7"
clap = "2.32"
lazy_static = "1.2"
log = "0.4"
memmap = "0.7"
fern = "0.5"
tptp = "0.7"
unique = "0.5"
