[package]
name = "lerna"
version = "0.1.0"
authors = ["Michael Rawson <michael@rawsons.uk>"]
description = "proves theorems"

[dependencies]
atomic = "0.4"
clap = "2.32"
crossbeam = "0.4"
fern = "0.5"
im = "12.0"
lazy_static = "1.1"
log = "0.4"
num_cpus = "1.8"
parking_lot = "0.6"
time = "0.1"
tptp = "0.5"
rand = "0.5"
