[package]
name = "lerna"
version = "0.1.0"
authors = ["Michael Rawson <michael@rawsons.uk>"]
description = "proves theorems"

[dependencies]
atomic = "0.4"
clap = "2.32"
im = "12.0"
log = "0.4"
parking_lot = "0.6"
time = "0.1"
tptp = "0.3"
rand = "0.5"

[dependencies.fern]
version = "0.5"
features = ["colored"]
